[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="page" type="org.springframework.data.domain.Page" --]
[#-- @ftlvariable name="site" type="com.wenwo.config.SiteConfig" --]
[#-- @ftlvariable name="model" type="com.wenwo.core.base.BaseEntity" --]
[#-- @ftlvariable name="topic" type="com.wenwo.module.topic.model.Topic" --]
[#-- @ftlvariable name="user" type="com.wenwo.module.user.model.User" --]
[#-- @ftlvariable name="comment" type="com.wenwo.module.comment.model.Comment" --]
[#-- @ftlvariable name="sec" type="com.wenwo.config.SecurityConfig" --]
[#-- @ftlvariable name="log" type="com.wenwo.module.log.model.Log" --]
[#-- @ftlvariable name="tag" type="com.wenwo.module.tag.model.Tag" --]